### ISSUE TITLE
Selector does not show on Safari browser

### ISSUE THREAD

**Issue by asafart** [chrisboustead/videojs-hls-quality-selector#12] opened 2019-05-22 13:47 UTC
Hi there,
For some reason, this plugin will not work on safari and when enabling the plugin it will show the Caption button instead of the Quality button.
Any idea on how to approach this?
Regards,
asaf

**Comment by asafart** [comment] 2019-05-22 14:01
I'm using the latest version of video js

**Comment by laptrinhcomvn** [comment] 2019-07-10 20:54
It's still not support Safari yet.

**Comment by chrisboustead** [comment] 2019-10-11 19:13
Closing as duplicate of #13

**Closed by chrisboustead** 2019-10-11 19:13 UTC

**Comment by uguraktas** [comment] 2021-01-20 07:47
> Closing as duplicate of #13

Not same topic, This topic about safari! 

Any solution about this?
